/**
 * 默认模型价格表（USD per 1M tokens）
 * 数据源：cc-switch src-tauri/src/database/schema.rs:seed_model_pricing
 * 维护：手动同步；用户可在 UsageStatsDashboard pricing tab 覆盖
 *
 * 注意：包含带日期后缀的精确 ID（如 claude-sonnet-4-5-20250929）和
 * 不带日期后缀的常用别名（如 claude-sonnet-4-5）。findPricingRule 会通过候选
 * 降级自动匹配，但显式别名可加速首次命中并避免前缀误匹配。
 */
export interface DefaultPricingEntry {
  modelId: string
  displayName: string
  inputUsdPerMillion: number
  outputUsdPerMillion: number
  cacheReadUsdPerMillion: number
  cacheCreationUsdPerMillion: number
}

export const DEFAULT_PRICING_RULES: DefaultPricingEntry[] = [
  { modelId: "claude-3-5-haiku-20241022", displayName: "Claude 3.5 Haiku", inputUsdPerMillion: 0.8, outputUsdPerMillion: 4.0, cacheReadUsdPerMillion: 0.08, cacheCreationUsdPerMillion: 1.0 },
  { modelId: "claude-3-5-sonnet-20241022", displayName: "Claude 3.5 Sonnet", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.3, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-fable-5", displayName: "Claude Fable 5", inputUsdPerMillion: 10.0, outputUsdPerMillion: 50.0, cacheReadUsdPerMillion: 1.0, cacheCreationUsdPerMillion: 12.5 },
  { modelId: "claude-haiku-4-5-20251001", displayName: "Claude Haiku 4.5", inputUsdPerMillion: 1.0, outputUsdPerMillion: 5.0, cacheReadUsdPerMillion: 0.1, cacheCreationUsdPerMillion: 1.25 },
  { modelId: "claude-mythos-5", displayName: "Claude Mythos 5", inputUsdPerMillion: 10.0, outputUsdPerMillion: 50.0, cacheReadUsdPerMillion: 1.0, cacheCreationUsdPerMillion: 12.5 },
  { modelId: "claude-opus-4-1-20250805", displayName: "Claude Opus 4.1", inputUsdPerMillion: 15.0, outputUsdPerMillion: 75.0, cacheReadUsdPerMillion: 1.5, cacheCreationUsdPerMillion: 18.75 },
  { modelId: "claude-opus-4-20250514", displayName: "Claude Opus 4", inputUsdPerMillion: 15.0, outputUsdPerMillion: 75.0, cacheReadUsdPerMillion: 1.5, cacheCreationUsdPerMillion: 18.75 },
  { modelId: "claude-opus-4-5-20251101", displayName: "Claude Opus 4.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-opus-4-6-20260206", displayName: "Claude Opus 4.6", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-opus-4-7", displayName: "Claude Opus 4.7", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-opus-4-8", displayName: "Claude Opus 4.8", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-sonnet-4-20250514", displayName: "Claude Sonnet 4", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.3, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-sonnet-4-5-20250929", displayName: "Claude Sonnet 4.5", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.3, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-sonnet-4-6-20260217", displayName: "Claude Sonnet 4.6", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.3, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "codex-mini", displayName: "Codex Mini", inputUsdPerMillion: 0.75, outputUsdPerMillion: 3.0, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-4.1", displayName: "GPT-4.1", inputUsdPerMillion: 2.0, outputUsdPerMillion: 8.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-4.1-mini", displayName: "GPT-4.1 Mini", inputUsdPerMillion: 0.4, outputUsdPerMillion: 1.6, cacheReadUsdPerMillion: 0.1, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-4.1-nano", displayName: "GPT-4.1 Nano", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.4, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5", displayName: "GPT-5", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-high", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-low", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-medium", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-mini", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-mini-high", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-codex-mini-medium", displayName: "GPT-5 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-high", displayName: "GPT-5", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-low", displayName: "GPT-5", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-medium", displayName: "GPT-5", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-mini", displayName: "GPT-5 Mini", inputUsdPerMillion: 0.25, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-minimal", displayName: "GPT-5", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5-nano", displayName: "GPT-5 Nano", inputUsdPerMillion: 0.05, outputUsdPerMillion: 0.4, cacheReadUsdPerMillion: 0.005, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1", displayName: "GPT-5.1", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-codex", displayName: "GPT-5.1 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-codex-max", displayName: "GPT-5.1 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-codex-max-high", displayName: "GPT-5.1 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-codex-max-xhigh", displayName: "GPT-5.1 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-codex-mini", displayName: "GPT-5.1 Codex", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-high", displayName: "GPT-5.1", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-low", displayName: "GPT-5.1", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-medium", displayName: "GPT-5.1", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.1-minimal", displayName: "GPT-5.1", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2", displayName: "GPT-5.2", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-codex", displayName: "GPT-5.2 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-codex-high", displayName: "GPT-5.2 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-codex-low", displayName: "GPT-5.2 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-codex-medium", displayName: "GPT-5.2 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-codex-xhigh", displayName: "GPT-5.2 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-high", displayName: "GPT-5.2", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-low", displayName: "GPT-5.2", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-medium", displayName: "GPT-5.2", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.2-xhigh", displayName: "GPT-5.2", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.3-codex", displayName: "GPT-5.3 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.3-codex-high", displayName: "GPT-5.3 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.3-codex-low", displayName: "GPT-5.3 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.3-codex-medium", displayName: "GPT-5.3 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.3-codex-xhigh", displayName: "GPT-5.3 Codex", inputUsdPerMillion: 1.75, outputUsdPerMillion: 14.0, cacheReadUsdPerMillion: 0.175, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.4", displayName: "GPT-5.4", inputUsdPerMillion: 2.5, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.25, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", inputUsdPerMillion: 0.75, outputUsdPerMillion: 4.5, cacheReadUsdPerMillion: 0.075, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.4-nano", displayName: "GPT-5.4 Nano", inputUsdPerMillion: 0.2, outputUsdPerMillion: 1.25, cacheReadUsdPerMillion: 0.02, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5-high", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5-low", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5-medium", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5-minimal", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-5.5-xhigh", displayName: "GPT-5.5", inputUsdPerMillion: 5.0, outputUsdPerMillion: 30.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o1", displayName: "OpenAI o1", inputUsdPerMillion: 15.0, outputUsdPerMillion: 60.0, cacheReadUsdPerMillion: 7.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o1-mini", displayName: "OpenAI o1-mini", inputUsdPerMillion: 0.55, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.55, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-2.0-flash", displayName: "Gemini 2.0 Flash", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.4, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", inputUsdPerMillion: 0.3, outputUsdPerMillion: 2.5, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash Lite", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.4, cacheReadUsdPerMillion: 0.01, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro", inputUsdPerMillion: 1.25, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.125, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3-flash-preview", displayName: "Gemini 3 Flash Preview", inputUsdPerMillion: 0.5, outputUsdPerMillion: 3.0, cacheReadUsdPerMillion: 0.05, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3-pro-preview", displayName: "Gemini 3 Pro Preview", inputUsdPerMillion: 2.0, outputUsdPerMillion: 12.0, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3.1-flash-lite", displayName: "Gemini 3.1 Flash Lite", inputUsdPerMillion: 0.25, outputUsdPerMillion: 1.5, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash Lite Preview", inputUsdPerMillion: 0.25, outputUsdPerMillion: 1.5, cacheReadUsdPerMillion: 0.025, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro Preview", inputUsdPerMillion: 2.0, outputUsdPerMillion: 12.0, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash", inputUsdPerMillion: 1.5, outputUsdPerMillion: 9.0, cacheReadUsdPerMillion: 0.15, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-chat", displayName: "DeepSeek Chat", inputUsdPerMillion: 0.27, outputUsdPerMillion: 1.1, cacheReadUsdPerMillion: 0.07, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-reasoner", displayName: "DeepSeek Reasoner", inputUsdPerMillion: 0.55, outputUsdPerMillion: 2.19, cacheReadUsdPerMillion: 0.14, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-v3", displayName: "DeepSeek V3", inputUsdPerMillion: 0.28, outputUsdPerMillion: 1.11, cacheReadUsdPerMillion: 0.028, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-v3.1", displayName: "DeepSeek V3.1", inputUsdPerMillion: 0.55, outputUsdPerMillion: 1.67, cacheReadUsdPerMillion: 0.055, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-v3.2", displayName: "DeepSeek V3.2", inputUsdPerMillion: 0.28, outputUsdPerMillion: 0.42, cacheReadUsdPerMillion: 0.028, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", inputUsdPerMillion: 0.14, outputUsdPerMillion: 0.28, cacheReadUsdPerMillion: 0.0028, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", inputUsdPerMillion: 0.435, outputUsdPerMillion: 0.87, cacheReadUsdPerMillion: 0.003625, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "codestral-2508", displayName: "Codestral", inputUsdPerMillion: 0.3, outputUsdPerMillion: 0.9, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "command-a", displayName: "Cohere Command A", inputUsdPerMillion: 2.5, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "command-r", displayName: "Cohere Command R", inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.6, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "command-r-plus", displayName: "Cohere Command R+", inputUsdPerMillion: 2.5, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "devstral-2-2512", displayName: "Devstral 2", inputUsdPerMillion: 0.4, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.04, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "devstral-medium", displayName: "Devstral Medium", inputUsdPerMillion: 0.4, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.04, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "devstral-small-1.1", displayName: "Devstral Small 1.1", inputUsdPerMillion: 0.07, outputUsdPerMillion: 0.28, cacheReadUsdPerMillion: 0.01, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "devstral-small-2-2512", displayName: "Devstral Small 2", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.3, cacheReadUsdPerMillion: 0.01, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-2-0-code", displayName: "Doubao Seed 2.0 Code", inputUsdPerMillion: 0.47, outputUsdPerMillion: 2.37, cacheReadUsdPerMillion: 0.09, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-2-0-code-preview-latest", displayName: "Doubao Seed 2.0 Code Preview", inputUsdPerMillion: 0.47, outputUsdPerMillion: 2.37, cacheReadUsdPerMillion: 0.09, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-2-0-lite", displayName: "Doubao Seed 2.0 Lite", inputUsdPerMillion: 0.08, outputUsdPerMillion: 0.5, cacheReadUsdPerMillion: 0.017, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-2-0-mini", displayName: "Doubao Seed 2.0 Mini", inputUsdPerMillion: 0.03, outputUsdPerMillion: 0.31, cacheReadUsdPerMillion: 0.0056, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-2-0-pro", displayName: "Doubao Seed 2.0 Pro", inputUsdPerMillion: 0.47, outputUsdPerMillion: 2.37, cacheReadUsdPerMillion: 0.09, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "doubao-seed-code", displayName: "Doubao Seed Code", inputUsdPerMillion: 0.17, outputUsdPerMillion: 1.11, cacheReadUsdPerMillion: 0.02, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "glm-4.6", displayName: "GLM-4.6", inputUsdPerMillion: 0.6, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.11, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "glm-4.7", displayName: "GLM-4.7", inputUsdPerMillion: 0.6, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.11, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "glm-5", displayName: "GLM-5", inputUsdPerMillion: 1.0, outputUsdPerMillion: 3.2, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "glm-5.1", displayName: "GLM-5.1", inputUsdPerMillion: 1.4, outputUsdPerMillion: 4.4, cacheReadUsdPerMillion: 0.26, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "glm-5.2", displayName: "GLM-5.2", inputUsdPerMillion: 1.4, outputUsdPerMillion: 4.4, cacheReadUsdPerMillion: 0.26, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-3", displayName: "Grok 3", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.75, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-3-mini", displayName: "Grok 3 Mini", inputUsdPerMillion: 0.25, outputUsdPerMillion: 0.5, cacheReadUsdPerMillion: 0.075, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4", displayName: "Grok 4", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.75, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4-1-fast-non-reasoning", displayName: "Grok 4.1 Fast", inputUsdPerMillion: 0.2, outputUsdPerMillion: 0.5, cacheReadUsdPerMillion: 0.05, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4-1-fast-reasoning", displayName: "Grok 4.1 Fast Reasoning", inputUsdPerMillion: 0.2, outputUsdPerMillion: 0.5, cacheReadUsdPerMillion: 0.05, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4.20-0309-non-reasoning", displayName: "Grok 4.20", inputUsdPerMillion: 1.25, outputUsdPerMillion: 2.5, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4.20-0309-reasoning", displayName: "Grok 4.20 Reasoning", inputUsdPerMillion: 1.25, outputUsdPerMillion: 2.5, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-4.3", displayName: "Grok 4.3", inputUsdPerMillion: 1.25, outputUsdPerMillion: 2.5, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-build-0.1", displayName: "Grok Build 0.1", inputUsdPerMillion: 1.0, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "grok-code-fast-1", displayName: "Grok Build 0.1 (Code Fast Alias)", inputUsdPerMillion: 1.0, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.2, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2-0905", displayName: "Kimi K2", inputUsdPerMillion: 0.55, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.1, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2-thinking", displayName: "Kimi K2 Thinking", inputUsdPerMillion: 0.55, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.1, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2-turbo", displayName: "Kimi K2 Turbo", inputUsdPerMillion: 1.11, outputUsdPerMillion: 8.06, cacheReadUsdPerMillion: 0.14, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2.5", displayName: "Kimi K2.5", inputUsdPerMillion: 0.6, outputUsdPerMillion: 3.0, cacheReadUsdPerMillion: 0.1, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2.6", displayName: "Kimi K2.6", inputUsdPerMillion: 0.95, outputUsdPerMillion: 4.0, cacheReadUsdPerMillion: 0.16, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "kimi-k2.7-code", displayName: "Kimi K2.7 Code", inputUsdPerMillion: 0.95, outputUsdPerMillion: 4.0, cacheReadUsdPerMillion: 0.19, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "magistral-medium", displayName: "Magistral Medium", inputUsdPerMillion: 2.0, outputUsdPerMillion: 5.0, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "magistral-small", displayName: "Magistral Small", inputUsdPerMillion: 0.5, outputUsdPerMillion: 1.5, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mimo-v2-flash", displayName: "MiMo V2 Flash", inputUsdPerMillion: 0.09, outputUsdPerMillion: 0.29, cacheReadUsdPerMillion: 0.009, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mimo-v2-pro", displayName: "MiMo V2 Pro", inputUsdPerMillion: 0.435, outputUsdPerMillion: 0.87, cacheReadUsdPerMillion: 0.0036, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mimo-v2.5", displayName: "MiMo V2.5", inputUsdPerMillion: 0.14, outputUsdPerMillion: 0.29, cacheReadUsdPerMillion: 0.0028, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mimo-v2.5-pro", displayName: "MiMo V2.5 Pro", inputUsdPerMillion: 0.435, outputUsdPerMillion: 0.87, cacheReadUsdPerMillion: 0.0036, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2", displayName: "MiniMax M2", inputUsdPerMillion: 0.27, outputUsdPerMillion: 0.95, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2.1", displayName: "MiniMax M2.1", inputUsdPerMillion: 0.27, outputUsdPerMillion: 0.95, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2.1-lightning", displayName: "MiniMax M2.1 Lightning", inputUsdPerMillion: 0.27, outputUsdPerMillion: 2.33, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2.5", displayName: "MiniMax M2.5", inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.95, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2.5-lightning", displayName: "MiniMax M2.5 Lightning", inputUsdPerMillion: 0.3, outputUsdPerMillion: 2.4, cacheReadUsdPerMillion: 0.03, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "minimax-m2.7", displayName: "MiniMax M2.7", inputUsdPerMillion: 0.3, outputUsdPerMillion: 1.2, cacheReadUsdPerMillion: 0.06, cacheCreationUsdPerMillion: 0.375 },
  { modelId: "minimax-m2.7-highspeed", displayName: "MiniMax M2.7 Highspeed", inputUsdPerMillion: 0.6, outputUsdPerMillion: 2.4, cacheReadUsdPerMillion: 0.06, cacheCreationUsdPerMillion: 0.375 },
  { modelId: "minimax-m3", displayName: "MiniMax M3", inputUsdPerMillion: 0.6, outputUsdPerMillion: 2.4, cacheReadUsdPerMillion: 0.12, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mistral-large-3-2512", displayName: "Mistral Large 3", inputUsdPerMillion: 0.5, outputUsdPerMillion: 1.5, cacheReadUsdPerMillion: 0.05, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mistral-medium-3.1", displayName: "Mistral Medium 3.1", inputUsdPerMillion: 0.4, outputUsdPerMillion: 2.0, cacheReadUsdPerMillion: 0.04, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mistral-medium-3.5", displayName: "Mistral Medium 3.5", inputUsdPerMillion: 1.5, outputUsdPerMillion: 7.5, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mistral-small-3.2-24b", displayName: "Mistral Small 3.2", inputUsdPerMillion: 0.075, outputUsdPerMillion: 0.2, cacheReadUsdPerMillion: 0.01, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "mistral-small-4", displayName: "Mistral Small 4", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.3, cacheReadUsdPerMillion: 0.01, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o3", displayName: "OpenAI o3", inputUsdPerMillion: 2.0, outputUsdPerMillion: 8.0, cacheReadUsdPerMillion: 0.5, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o3-mini", displayName: "OpenAI o3-mini", inputUsdPerMillion: 0.55, outputUsdPerMillion: 2.2, cacheReadUsdPerMillion: 0.55, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o3-pro", displayName: "OpenAI o3-pro", inputUsdPerMillion: 20.0, outputUsdPerMillion: 80.0, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "o4-mini", displayName: "OpenAI o4-mini", inputUsdPerMillion: 1.1, outputUsdPerMillion: 4.4, cacheReadUsdPerMillion: 0.275, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-235b-a22b", displayName: "Qwen3 235B-A22B", inputUsdPerMillion: 0.7, outputUsdPerMillion: 8.4, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-32b", displayName: "Qwen3 32B", inputUsdPerMillion: 0.16, outputUsdPerMillion: 0.64, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-coder-480b", displayName: "Qwen3 Coder 480B", inputUsdPerMillion: 0.65, outputUsdPerMillion: 3.25, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-coder-480b-a35b-instruct", displayName: "Qwen3 Coder 480B-A35B Instruct", inputUsdPerMillion: 0.65, outputUsdPerMillion: 3.25, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-coder-flash", displayName: "Qwen3 Coder Flash", inputUsdPerMillion: 0.195, outputUsdPerMillion: 0.975, cacheReadUsdPerMillion: 0.039, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-coder-next", displayName: "Qwen3 Coder Next", inputUsdPerMillion: 0.12, outputUsdPerMillion: 0.75, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-coder-plus", displayName: "Qwen3 Coder Plus", inputUsdPerMillion: 0.65, outputUsdPerMillion: 3.25, cacheReadUsdPerMillion: 0.13, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3-max", displayName: "Qwen3 Max", inputUsdPerMillion: 0.78, outputUsdPerMillion: 3.9, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3.5-plus", displayName: "Qwen3.5 Plus", inputUsdPerMillion: 0.26, outputUsdPerMillion: 1.56, cacheReadUsdPerMillion: 0.052, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3.6-plus", displayName: "Qwen3.6 Plus", inputUsdPerMillion: 0.325, outputUsdPerMillion: 1.95, cacheReadUsdPerMillion: 0.065, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3.7-max", displayName: "Qwen3.7 Max", inputUsdPerMillion: 2.5, outputUsdPerMillion: 7.5, cacheReadUsdPerMillion: 0.25, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwen3.7-plus", displayName: "Qwen3.7 Plus", inputUsdPerMillion: 0.4, outputUsdPerMillion: 1.6, cacheReadUsdPerMillion: 0.08, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwq-32b", displayName: "QwQ 32B", inputUsdPerMillion: 0.2, outputUsdPerMillion: 0.6, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "qwq-plus", displayName: "QwQ Plus", inputUsdPerMillion: 0.8, outputUsdPerMillion: 2.4, cacheReadUsdPerMillion: 0.0, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "step-3.5-flash", displayName: "Step 3.5 Flash", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.3, cacheReadUsdPerMillion: 0.02, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "step-3.5-flash-2603", displayName: "Step 3.5 Flash 2603", inputUsdPerMillion: 0.1, outputUsdPerMillion: 0.3, cacheReadUsdPerMillion: 0.02, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "step-3.7-flash", displayName: "Step 3.7 Flash", inputUsdPerMillion: 0.19, outputUsdPerMillion: 1.13, cacheReadUsdPerMillion: 0.04, cacheCreationUsdPerMillion: 0.0 },
]

/**
 * 常用无日期后缀别名（undated aliases）。
 *
 * Anthropic API 返回的模型 ID 通常带日期（如 claude-sonnet-4-5-20250929），
 * 但用户在 binding / defaultBindings 中常用短名（如 claude-sonnet-4-5）。
 * 这些别名确保即使 findPricingRule 的候选降级未命中，精确匹配也能成功。
 *
 * 价格值取自同家族带日期版本的最新条目。
 */
export const DEFAULT_PRICING_ALIASES: DefaultPricingEntry[] = [
  // Claude 无日期别名
  { modelId: "claude-sonnet-4-5", displayName: "Claude Sonnet 4.5 (alias)", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.30, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-opus-4-5", displayName: "Claude Opus 4.5 (alias)", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.50, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-haiku-4-5", displayName: "Claude Haiku 4.5 (alias)", inputUsdPerMillion: 1.0, outputUsdPerMillion: 5.0, cacheReadUsdPerMillion: 0.10, cacheCreationUsdPerMillion: 1.25 },
  { modelId: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6 (alias)", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.30, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-opus-4-6", displayName: "Claude Opus 4.6 (alias)", inputUsdPerMillion: 5.0, outputUsdPerMillion: 25.0, cacheReadUsdPerMillion: 0.50, cacheCreationUsdPerMillion: 6.25 },
  { modelId: "claude-sonnet-4", displayName: "Claude Sonnet 4 (alias)", inputUsdPerMillion: 3.0, outputUsdPerMillion: 15.0, cacheReadUsdPerMillion: 0.30, cacheCreationUsdPerMillion: 3.75 },
  { modelId: "claude-opus-4", displayName: "Claude Opus 4 (alias)", inputUsdPerMillion: 15.0, outputUsdPerMillion: 75.0, cacheReadUsdPerMillion: 1.50, cacheCreationUsdPerMillion: 18.75 },
  // GPT 无日期别名（OpenAI 模型通常不带日期后缀，但保留以防万一）
  { modelId: "gpt-4o", displayName: "GPT-4o (alias)", inputUsdPerMillion: 2.5, outputUsdPerMillion: 10.0, cacheReadUsdPerMillion: 1.25, cacheCreationUsdPerMillion: 0.0 },
  { modelId: "gpt-4o-mini", displayName: "GPT-4o Mini (alias)", inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.6, cacheReadUsdPerMillion: 0.075, cacheCreationUsdPerMillion: 0.0 },
]
